### ISSUE TITLE
Exclude non-jar dependencies

### ISSUE THREAD

**Issue by thinkbigthings** [johnpoth/jshell-maven-plugin#1] opened 2018-04-12 17:20 UTC
If there are non-jar dependencies, the plugin will just fail to launch on invalid classpath argument. Is there a way to do the equivalent of -DincludeTypes=jar? I can't use this plugin in a project that has a .nar dependency.

**Comment by johnpoth** [comment] 2018-04-13 08:30
Hi @thinkbigthings, trying to reproduce by adding the nar dependency to my pom:
```
        <dependency>
          <groupId>org.apache.nifi</groupId>
          <artifactId>nifi-hadoop-libraries-nar</artifactId>
          <version>1.6.0</version>
          <type>nar</type>
        </dependency>
```

I am able to use the plugin and access the classes inside the .nar:
```
[INFO] --- jshell-maven-plugin:1.0:run (default-cli) @ foo ---
|  Welcome to JShell -- Version 9
|  For an introduction type: /help intro

jshell> new org.tukaani.xz.ARMOptions()
$1 ==> org.tukaani.xz.ARMOptions@7d0587f1

jshell> 
```

What is the error you are getting? Thanks!

**Comment by johnpoth** [comment] 2018-04-16 08:26
Hi @thinkbigthings, I am unable to reproduce the above error; would you have an easy way for me to reproduce? Perhaps a github repo?

Thanks!

**Comment by thinkbigthings** [comment] 2018-04-17 16:04
I'm trying this on a commercial product so I can't easily share a repo. I found something interesting though...

The project for which I'm running the maven jshell plugin (that references a nar dependency) itself calls the nar plugin (com.github.maven-nar:nar-maven-plugin:3.5.1) And when I comment out that nar plugin, the jshell plugin runs! I don't have an explanation.

**Comment by thinkbigthings** [comment] 2020-03-07 17:46
I suspect the issue was something to do with an interaction with the nar plugin as opposed to a nar dependency. But I'm not using that plugin anymore and it doesn't seem to be bothering anyone else. This issue is years old and hasn't been reproduced, do you want to close it?

**Comment by johnpoth** [comment] 2020-03-09 16:51
Sure we can close it and re-open it if something else comes up

**Closed by johnpoth** 2020-03-09 16:51 UTC
